apiVersion: v1
kind: Service
metadata:
  name: shopstack-backend-service
  namespace: shopstack
spec:
  type: ClusterIP
  selector:
    app: shopstack-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000