apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopstack-redis
  namespace: shopstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopstack-redis
  template:
    metadata:
      labels:
        app: shopstack-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379