apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "shopstack.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "shopstack.backendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shopstack.commonLabels" . | nindent 8 }}
        {{- include "shopstack.backendSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.backend.image }}
          imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          envFrom:
            - configMapRef:
                name: shopstack-backend-config
            - secretRef:
                name: shopstack-backend-secret
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.readinessProbe.path }}
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.livenessProbe.path }}
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}