apiVersion: v1
kind: ConfigMap
metadata:
  name: shopstack-backend-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "shopstack.commonLabels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  DB_HOST: {{ .Values.config.DB_HOST | quote }}
  DB_PORT: {{ .Values.config.DB_PORT | quote }}
  DB_NAME: {{ .Values.config.DB_NAME | quote }}
  DB_USER: {{ .Values.config.DB_USER | quote }}
  REDIS_HOST: {{ .Values.config.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.config.REDIS_PORT | quote }}