apiVersion: v1
kind: Secret
metadata:
  name: shopstack-backend-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "shopstack.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}