apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.pvc.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "shopstack.commonLabels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgres.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.size }}