apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "shopstack.commonLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "shopstack.redisSelectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}