apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "shopstack.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      {{- include "shopstack.redisSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shopstack.commonLabels" . | nindent 8 }}
        {{- include "shopstack.redisSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.redis.name }}
          image: {{ .Values.redis.image }}
          imagePullPolicy: {{ .Values.redis.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.containerPort }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}