apiVersion: v1
kind: Secret
metadata:
  name: shopstack-postgres-secret
  namespace: shopstack
type: Opaque
stringData:
  POSTGRES_USER: "shopstack_user"
  POSTGRES_PASSWORD: "shopstack_dev_password"
  POSTGRES_DB: "shopstack"