apiVersion: v1
kind: Service
metadata:
  name: shopstack-frontend-service
  namespace: shopstack
spec:
  type: ClusterIP
  selector:
    app: shopstack-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80