config:
  APP_ENV: prod
  LOG_LEVEL: INFO

frontend:
  replicas: 2
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "150m"
      memory: "128Mi"
    limits:
      cpu: "400m"
      memory: "256Mi"

backend:
  replicas: 2
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

postgres:
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "700m"
      memory: "1Gi"

redis:
  replicas: 1
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

ingress:
  enabled: true