apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopstack-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/thisisratnesh/shopstack-k8s-gitops.git
    targetRevision: main
    path: helm/shopstack
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: shopstack-helm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true